name: Labeler

on: [pull_request]

jobs:
  size-labeler:
    runs-on: ubuntu-latest
    name: 'Label the PR'
    steps:
      # https://github.com/alexromer0/pull-request-labeler
      - name: Pull request size labelling
        uses: alexromer0/pull-request-labeler@2.1.1
        with:
          GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'
          xs_limit: '100'
          sm_limit: '200'
          md_limit: '400'
          lg_limit: '800'
